apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpu-shm-webhook-tls
  namespace: kube-system
spec:
  dnsNames:
  - gpu-shm-webhook.cluster.local
  - gpu-shm-webhook.kube-system.svc.cluster.local
  - gpu-shm-webhook
  - gpu-shm-webhook.kube-system
  - gpu-shm-webhook.kube-system.svc
  duration: 26280h
  renewBefore: 360h
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer-k8s-example-org
  secretName: gpu-shm-webhook-tls
